# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('poster', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=10)),
                ('releaseDate', models.CharField(default='', max_length=50)),
                ('rating', models.CharField(max_length=4)),
                ('n_raters', models.CharField(max_length=15)),
                ('trailer', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('url', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=datetime.date(2017, 11, 24))),
                ('actors', models.ManyToManyField(to='playmovies.Actor')),
                ('directors', models.ManyToManyField(to='playmovies.Director')),
                ('genre', models.ManyToManyField(to='playmovies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80)),
                ('name', models.CharField(default='', max_length=80)),
                ('description', models.TextField()),
                ('releaseDate', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cost', models.CharField(max_length=10)),
                ('url', models.CharField(default='', max_length=200)),
                ('episodes', models.ManyToManyField(to='playmovies.TVEpisode')),
            ],
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=4)),
                ('n_raters', models.CharField(max_length=15)),
                ('releaseDate', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date(2017, 11, 24))),
                ('category', models.ManyToManyField(to='playmovies.Genre')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmovies.TVSeason')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmovies.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(to='playmovies.Producer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(to='playmovies.Writer'),
        ),
        migrations.AddField(
            model_name='day',
            name='movies',
            field=models.ManyToManyField(to='playmovies.Movie'),
        ),
        migrations.AddField(
            model_name='day',
            name='tvseries',
            field=models.ManyToManyField(to='playmovies.TVSeries'),
        ),
    ]
