# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0002_auto_20171115_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='movie',
        ),
        migrations.AddField(
            model_name='day',
            name='movie',
            field=models.ManyToManyField(to='playmovies.Movie'),
        ),
    ]
