# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0003_auto_20171115_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
