# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0004_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='director',
            name='url',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='genre',
            name='url',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='producer',
            name='url',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='writer',
            name='url',
            field=models.CharField(default='', max_length=70),
        ),
    ]
