# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0008_auto_20171116_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieImage',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 18)),
        ),
    ]
