# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0009_auto_20171118_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
