# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0010_auto_20171118_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='producer',
            new_name='producers',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='writer',
            new_name='writers',
        ),
    ]
