# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0011_auto_20171118_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=4),
        ),
    ]
