# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0012_auto_20171118_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 19)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
