# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0013_auto_20171119_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='n_raters',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=300),
        ),
    ]
