# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 03:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0017_auto_20171119_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='releaseDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 20)),
        ),
    ]
