# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0018_auto_20171120_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='movie',
            new_name='movies',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 19)),
        ),
    ]
