# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmovies', '0019_auto_20171119_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('poster', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=10)),
                ('url', models.CharField(default='', max_length=200)),
                ('episodes', models.ManyToManyField(to='playmovies.TVEpisode')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='tvseries',
            field=models.ManyToManyField(to='playmovies.TVSeries'),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='category',
            field=models.ManyToManyField(to='playmovies.Genre'),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 22)),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='n_raters',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='poster',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='rating',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='releaseDate',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 22)),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='playmovies.TVSeason'),
            preserve_default=False,
        ),
    ]
